### ISSUE TITLE
Fix Documentation

### ISSUE THREAD

**Issue by suryasaitura-db** [amesar/mlflow-export-import#18]
Please change the syntax documentation for export and import experiments list with below:
1.  Sample example should specify the Experiments ID List with CSV separated without any spaces
python -u -m mlflow_export_import.experiment.export_experiment_list --experiments 1064719,1070385,1156896 --output-dir out_list

2. The syntax is "--experiments" with an "s"

**Comment by amesar** [comment]
Thanks for the eagle eyes. :) Fixed.
