### ISSUE TITLE
[Databricks] Feature request: create parent directories for experiments if they don't already exist

### ISSUE THREAD

**Issue by smurching** [amesar/mlflow-export-import#24]
In Databricks, it seems that experiment export/import requires the directories containing experiments in the source workspace to also be present in the destination workspace. For example, if I export an experiment at  `/Users/engineer@company.com/cool-experiment` from workspace A and import into workspace B, the folder `/Users/engineer@company.com` must exist in workspace B. 

### Recursively create parent directories
It'd be great to be able to provide an option to recursively create the parent directories for the experiments if needed - the downside of doing this is that the directories in workspace B would be owned by user importing the experiments, which could be confusing and b) it's not possible to create directories under the `/Users` folder & attempting to do so fails with the following error:

```
$ databricks  --profile dogfood workspace mkdirs /Users/sid-test-directory     
Error: b'{"error_code":"DIRECTORY_PROTECTED","message":"Folder Users is protected"}'
```

**Comment by amesar** [comment]
Have pushed a fix that creates the parent workspace directories for a Databricks import.

**Comment by amesar** [comment]
The user_id for a Databricks MLflow import has different semantics than the open source MLflow import. With OSS MLflow you can arbitrarily set the "user_id" field for run.info. For Databricks you cannot - it is picked up from the given user importing the run/experiment. Therefore, for an admin importing all the experiments of a workspace with different users, cannot preserver the original use owners. We need a new feature to do this.

**Comment by amesar** [comment]
Fixed.
