### ISSUE TITLE
Metrics Export

### ISSUE THREAD

**Issue by gaurangv99** [amesar/mlflow-export-import#26]
While exporting experiment i.e.
python -u -m mlflow_export_import.experiment.export_experiment \
  --experiment sklearn-wine \
  --output-dir out
  --export-metadata-tags True
only the latest metric value is exported.
so if in a run we have 1000 steps and if all the steps are logged only the latest value of metric is recorded in the export.
Is there a way to get metric data for all the steps?

**Comment by amesar** [comment]
@gaurangv99 I just checked in a fix. Let me know if it works for you. Sorry for the delay.
