### ISSUE TITLE
Inconsistent handling/support of different filesystems for export/import across modules

### ISSUE THREAD

**Issue by smurching** [amesar/mlflow-export-import#28]
For example, it looks like the `RunExporter` class can export to either `dbfs:/...` paths (if running on Databricks) or the local filesystem, but `RunImporter` can only run against local paths, so if writing code that exports to `dbfs:/...` paths you may need to write logic to convert the paths into DBFS FUSE paths (`/dbfs/...`) so that `RunImporter` can subsequently import from them.

**Comment by amesar** [comment]
Just fixed a bug - is this is what you are referring to?

https://github.com/amesar/mlflow-export-import/blob/master/mlflow_export_import/run/import_run.py#L64

Commit: [93b4f3f75f6e8f6d2ca443f8857f98ea510bf22b](https://github.com/amesar/mlflow-export-import/commit/93b4f3f75f6e8f6d2ca443f8857f98ea510bf22b)

**Comment by amesar** [comment]
Fixed.
