### ISSUE TITLE
Create run artifact export directory automatically during run export

### ISSUE THREAD

**Issue by smurching** [amesar/mlflow-export-import#36]
Will add some details here shortly!

**Comment by amesar** [comment]
The output export directory is automatically created for all MLflow objects.

For runs see: https://github.com/amesar/mlflow-export-import/blob/master/mlflow_export_import/run/export_run.py#L32

**Comment by smurching** [comment]
@amesar sorry for the noise here, I just retried & found that indeed the run output export directory was already created + there was no need to do extra work to create an `artifacts` subdirectory under the export directory as the MLflow client automatically creates it - will go ahead & close this!
