### ISSUE TITLE
How to not lose the run_id while importing exporting?

### ISSUE THREAD

**Issue by KuenstlicheIntelligenz** [amesar/mlflow-export-import#42]
Hey,

I noticed, while exporting importing, the run_id changes. Maybe im doing something wrong.
How can i keep it, so that i can use my runs with mlflow?
For example, we evaluate the model in a later process where certain runs that are listed in an sql table. These wont work anymore if i try to migrate with a changing run_id...

Im trying migrate from local backend to sql backend

**Comment by amesar** [comment]
Run IDs are auto-generated UUIDs so there is no way to preserve it. The recommended approach is to access models for scoring using the model registry with stage names. For example, use _models:/sklearn_wine/production_ instead of _runs:/4f702536b5d24d609668a7a566ec6bd6/sklearn_wine_.

**Comment by amesar** [comment]
If you set the option `--export-metadata-tags=True` on the `export-experiment`tool it will the original metadata that is auto-generate with a `mlflow_export_import.metadata` prefix. For example:
    `"mlflow_export_import.metadata.run_id": "c7d570a1d1c2410ba4e690aeaaea89b4",`
