### ISSUE TITLE
Can not import into Databrick Mlflow

### ISSUE THREAD

**Issue by damienrj** [amesar/mlflow-export-import#44]
I exported all of the experiments from our open source mlflow, and that didn't have any issues.  However when I try to import the experiments into our databricks managed mlflow I get the error
```bash
❯ import-experiments --input-dir "out" --experiment-name-prefix imported_
MLflow Tracking URI: databricks
Options:
  input_dir: out
  experiment_name_prefix: imported_
  use_src_user_id: False
  import_mlflow_tags: True
  import_metadata_tags: False
  use_threads: False
   {'id': '2', 'name': 'personalized-messages', 'ok_runs': 7, 'failed_runs': 0, 'duration': 15.0}
in_databricks: False
importing_into_databricks: True
MLflowClient: databricks
Creating Databricks workspace directory ''
Traceback (most recent call last):
  File "/Users/damien/Development/mlflow-export-import/mlflow_export_import/bulk/import_experiments.py", line 14, in _import_experiment
    importer.import_experiment(exp_name, exp_input_dir)
  File "/Users/damien/Development/mlflow-export-import/mlflow_export_import/experiment/import_experiment.py", line 35, in import_experiment
    mlflow_utils.set_experiment(self.dbx_client, exp_name)
  File "/Users/damien/Development/mlflow-export-import/mlflow_export_import/common/mlflow_utils.py", line 52, in set_experiment
    dbx_client.post("workspace/mkdirs", { "path": exp_dir })
  File "/Users/damien/Development/mlflow-export-import/mlflow_export_import/common/http_client.py", line 50, in post
    return json.loads(self._post(resource, data).text)
  File "/Users/damien/Development/mlflow-export-import/mlflow_export_import/common/http_client.py", line 46, in _post
    self._check_response(rsp,uri)
  File "/Users/damien/Development/mlflow-export-import/mlflow_export_import/common/http_client.py", line 63, in _check_response
    raise MlflowExportImportException(f"HTTP status code: {rsp.status_code}. Reason: {rsp.reason}. URI: {uri}. Params: {params}.")
mlflow_export_import.common.MlflowExportImportException: HTTP status code: 400. Reason: Bad Request. URI: https://xxxxxxxx.databricks.com/api/2.0/workspace/mkdirs. Params: None.
```
I believe the issue is that the location of the workspace directory is `/Users/<USER>/my-experiment` so it is failing because it is trying to write to the root directory.

**Comment by amesar** [comment]
Get rid  of the option `--experiment_name_prefix: imported_`. Can't use prefixes when importing into Databricks workspaces since that's going to be an illegal workspace path. Yes, need better doc for that.

**Comment by Tfeinstein24** [comment]
@damienrj how did you configure the tool to see your open source mlflow? I'm getting this error:

`WARNING: You haven't configured the CLI yet! Please configure by entering `/databricks/python3/bin/export-model configure`

**Comment by amesar** [comment]
Make sure you are using the Databricks ML Runtime.

**Comment by damienrj** [comment]
I can say with the most recent version I have been able to to successfully important GBs of data. The only caveat is I can't use the bulk import took since I need to set the experiment name to match the requirements of databricks. `/Users/<USER>/my-experiment` for example.

**Comment by damienrj** [comment]
> @damienrj how did you configure the tool to see your open source mlflow? I'm getting this error:
> 
> `WARNING: You haven't configured the CLI yet! Please configure by entering `/databricks/python3/bin/export-model configure`

I set tracking to point to my open source endpoint, and then for importing set it to databricks.

**Comment by maltequast** [comment]
I was running into the same error. Solution for me was to use my Users folder. The import path works slightly different than on open source mlflow.

Hope it helps anyone who runs into it.
