### ISSUE TITLE
How to configure http-client to import from an mlflow server to Databricks

### ISSUE THREAD

**Issue by Tfeinstein24** [amesar/mlflow-export-import#48]
Hello, I am trying to import models from one managed mlflow server to databricks.  I am getting this error after running in databricks notebook:

`%sh
http-client --api https://<HOST REDACTED>/ --resource 'experiments/list'`

error:
`WARNING: You haven't configured the CLI yet! Please configure by entering `/databricks/python3/bin/http-client configure`
Traceback (most recent call last):
  File "/databricks/python3/bin/http-client", line 8, in <module>
    sys.exit(main())
  File "/databricks/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/databricks/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/databricks/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/databricks/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/databricks/python3/lib/python3.8/site-packages/mlflow_export_import/common/http_client.py", line 100, in main
    client = DatabricksHttpClient() if api == "databricks" else MlflowHttpClient()
  File "/databricks/python3/lib/python3.8/site-packages/mlflow_export_import/common/http_client.py", line 74, in __init__
    super().__init__("api/2.0/mlflow", host, token)
  File "/databricks/python3/lib/python3.8/site-packages/mlflow_export_import/common/http_client.py", line 21, in __init__
    raise MlflowExportImportException("MLflow host or token is not configured correctly")
mlflow_export_import.common.MlflowExportImportException: MLflow host or token is not configured correctly`

How to I correctly configure the http-client to point at the mlflow server that I want to import from?

**Comment by Tfeinstein24** [comment]
Hi Andre, thanks for the reply.

I have installed your package in Databricks itself in a notebook. I am able
to export a model from another tracking server (not Databricks) into a
staging area inside Databricks.

My problem I’m having is when I use your import-mode tool. I’m getting a
not authorized error wrapped in html. Have you seen this before?

**Comment by amesar** [comment]
Check to make sure you have correct Databricks personal access token.

**Comment by Tfeinstein24** [comment]
@amesar This is the error I'm getting when trying to import into Databricks:

`mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/preview/mlflow/registered-models/create failed with error code 401 != 200. Response body: '<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 401 Unauthorized</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /api/2.0/preview/mlflow/registered-models/create. Reason:
<pre>    Unauthorized</pre></p>
</body>
</html>`

My setup looks like this:
`%sh
MLFLOW_TRACKING_URI=tracking uri redacted
DATABRICKS_HOST=host redacted
DATABRICKS_TOKEN=token redacted 
import-model --model ExampleModel --input-dir /dbfs/ExampleModel/test --experiment-name test`

**Comment by amesar** [comment]
Are you trying to execute the script from a Databricks notebook? I have never tried that. Try using the export-import notebooks instead.
https://github.com/amesar/mlflow-export-import/tree/master/databricks_notebooks

**Comment by Tfeinstein24** [comment]
Will this work if I am importing from a tracking server (not databricks) into a databricks tracking server?

**Comment by amesar** [comment]
Use the CLI tools to import from OSS tracking server into DB tracking server.

**Comment by Tfeinstein24** [comment]
Thank you, I almost have this working fully. I am able to import everything using the CLI tool except I am getting an error when bringing the .pkl (pickle) file over:

`ERROR: run_id: <REDACTED> Exception: The following failures occurred while downloading one or more artifacts from s3://<REDACTED>/artifacts: {'<REDACTED>/python_model.pkl': "OSError(95, 'Operation not supported')"}`

I am running this CLI command in the notebook:

`export MLFLOW_TRACKING_URI=<REDACTED>/
export-run --run-id "$RUN_ID" --output-dir "$FILE_PATH"`

**Comment by amesar** [comment]
Are your Databricks artifacts stored in DBFS or directly in S3? For S3, you need to have your AWS credentials set up correctly. I've only tested with DBFS artifacts, haven't done any direct S3 tests. You may want to verify your S3 artifact with the [download_artifacts](https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.download_artifacts) API method.

**Comment by amesar** [comment]
A stack trace would also be helpful.

**Comment by Tfeinstein24** [comment]
@amesar

`Traceback (most recent call last):
  File "/databricks/python3/lib/python3.8/site-packages/mlflow_export_import/run/export_run.py", line 72, in export_run
    self.mlflow_client.download_artifacts(run.info.run_id,"", dst_path=mk_local_path(dst_path))
  File "/databricks/python3/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1413, in download_artifacts
    return self._tracking_client.download_artifacts(run_id, path, dst_path)
  File "/databricks/python3/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 391, in download_artifacts
    return self._get_artifact_repo(run_id).download_artifacts(path, dst_path)
  File "/databricks/python3/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repo.py", line 265, in download_artifacts
    raise MlflowException(
mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from s3://<REDACTED>/artifacts: {'<REDACTED>/python_model.pkl': "OSError(95, 'Operation not supported')"}
MLflow Version: 1.24.0
MLflow Tracking URI: https://<REDACTED>/
Options:
  run_id: <REDACTED>  output_dir: /dbfs/<REDACTED>/
  export_metadata_tags: False
  notebook_formats: 
Databricks REST client: https://<REDACTED>/api/2.0
ERROR: run_id: <REDACTED> Exception: The following failures occurred while downloading one or more artifacts from s3://<REDACTED>/artifacts: {'<REDACTED>/python_model.pkl': "OSError(95, 'Operation not supported')"}`

**Comment by Tfeinstein24** [comment]
@amesar Also, the artifacts are in S3. The AWS creds are set up correctly because I'm able to pull every file but the pickle file.

**Comment by amesar** [comment]
Stack trace doesn't really indicate what went wrong. See if this works. mlflow-export-import just calls the public MLflow API.
```
import sys
import mlflow
run_id = sys.argv[1]
path = sys.argv[2] if len(sys.argv) >= 2 else ""
client = mlflow.tracking.MlflowClient()
client.download_artifacts(run_id, path)
```
