### ISSUE TITLE
Enhancement Request: Flags to continue after error that outputs the error to the screen, or to a error log

### ISSUE THREAD

**Issue by nateanth** [amesar/mlflow-export-import#8]
When running this toolkit, any error experienced will stop the script dead in its tracks.   For example:

If it encounters any data that was outside of expectation it fails and there is no continue on failure. 

Examples:

- Export all experiments and one of the experiments has no runs associated with it, the job will fail and will stop downloading all experiments.
- When importing a job with multiple runs. If there is an incident with 1 out of 200 runs the entire import process fails.

Flags to continue after error that outputs the error to the screen, or some other location, would solve most issues.

**Comment by amesar** [comment]
Sounds like a good idea. Let me look into it.

**Comment by amesar** [comment]
Done
