### ISSUE TITLE
DBFS Path Issue on Windows Based Systems.

### ISSUE THREAD

**Issue by TylerRayKillian** [amesar/mlflow-export-import#9]
When importing models using a Windows based system it flips the slash in the path. 
**Example:**
'dbfs:/databricks/mlflow-tracking/11111/111111/artifacts\test'

Should be
'dbfs:/databricks/mlflow-tracking/11111/111111/artifacts/test'

 File "C:\Program Files\Python37\lib\site-packages\mlflow\utils\rest_utils.py", line 122, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid source 'dbfs:/databricks/mlflow-tracking/11111/111111/artifacts\test'. Only DBFS locations are currently supported.

**Comment by amesar** [comment]
Fixed with commit https://github.com/amesar/mlflow-export-import/commit/8a033cbbf895fa3e608fd101b1be44440286e45d

**Comment by amesar** [comment]
Fixed with commit https://github.com/amesar/mlflow-export-import/commit/8a033cbbf895fa3e608fd101b1be44440286e45d
